language: scala
scala:
  - 2.11.8

sudo: required
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - ./docker/provision.sh

# for deploy
before_deploy: ./dist-cli.sh
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: ./.dist-work/zabbicook-$TRAVIS_TAG.zip
  on:
    tags: true
